easy_admin:
    entities:
#        # List the entity class name you want to manage
         - App\Entity\Livres
         - App\Entity\Auteurs
         - App\Entity\Editeurs
         - App\Entity\Fournisseurs
         - App\Entity\Genres
         - App\Entity\Heros
